services:
  - type: web
    name: myshop-api
    env: docker
    plan: free
    branch: main # or 'master' — change if needed
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: CONNECTIONSTRINGS__DEFAULTCONNECTION
        fromDatabase:
          name: myshop-db
          property: connectionString

databases:
  - name: myshop-db
    plan: free
    databaseName: myshop
    user: myshop_user
